name: go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REDIS_URL: "redis://redis_sidecar:6379"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go build .
      - run: go vet
      - run: go test -v ./...
    services:
      redis_sidecar:
        image: redis