name: go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REDIS_URL: "redis://redis_sidecar:6379"
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.18-alpine
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: go build .
      - run: go vet
      - run: go test -v ./...
    services:
      redis_sidecar:
        image: redis
        env:
          REDIS_REPLICATION_MODE: master